AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  Stage:
    Type: String
    Description: Environment stage or git branch
  LogRetentionInDays:
    Type: Number
    Default: 14
    Description: CloudWatch Logs retention period
  SharedLibsLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project shared libraries Lambda Layer ARN
Globals:
  Function:
    Timeout: 10
    Tracing: Active
    MemorySize: 512
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: payment
        POWERTOOLS_METRICS_NAMESPACE: ServerlessAirline
        LOG_LEVEL: INFO
Resources:
  StripePaymentApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:375983427419:applications/api-lambda-stripe-charge
        SemanticVersion: 4.4.1
      Parameters:
        EnableInstantCapture: 'false'
        SSMParameterPath:
          Fn::Sub: ${Stage}/service/payment/stripe/secretKey
  CollectPayment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ServerlessAirline-CollectPayment-${Stage}
      Handler: collect.lambda_handler
      Runtime: python3.7
      CodeUri: s3://amplify-flighttrip-dev-152829-deployment/6f86e1e4100f8913cf0f78318166ab4d
      Layers:
      - Ref: SharedLibsLayer
      Environment:
        Variables:
          PAYMENT_API_URL:
            Fn::GetAtt:
            - StripePaymentApplication
            - Outputs.CaptureApiUrl
          STAGE:
            Ref: Stage
  RefundPayment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ServerlessAirline-RefundPayment-${Stage}
      Handler: refund.lambda_handler
      CodeUri: s3://amplify-flighttrip-dev-152829-deployment/e791936ecb5212701f8599c820fa6a6c
      Runtime: python3.7
      Layers:
      - Ref: SharedLibsLayer
      Environment:
        Variables:
          PAYMENT_API_URL:
            Fn::GetAtt:
            - StripePaymentApplication
            - Outputs.RefundApiUrl
          STAGE:
            Ref: Stage
  RefundPaymentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${RefundPayment}
      RetentionInDays:
        Ref: LogRetentionInDays
  CollectPaymentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${CollectPayment}
      RetentionInDays:
        Ref: LogRetentionInDays
  CollectPaymentParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /${Stage}/service/payment/function/collect
      Description: Collect Payment Lambda ARN
      Type: String
      Value:
        Fn::Sub: ${CollectPayment.Arn}
  RefundPaymentParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /${Stage}/service/payment/function/refund
      Description: Refund Payment Lambda ARN
      Type: String
      Value:
        Fn::Sub: ${RefundPayment.Arn}
  PaymentCaptureEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /${Stage}/service/payment/api/capture/url
      Type: String
      Value:
        Fn::Sub: ${StripePaymentApplication.Outputs.CaptureApiUrl}
  PaymentChargeEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /${Stage}/service/payment/api/charge/url
      Type: String
      Value:
        Fn::Sub: ${StripePaymentApplication.Outputs.ChargeApiUrl}
  PaymentRefundEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /${Stage}/service/payment/api/refund/url
      Type: String
      Value:
        Fn::Sub: ${StripePaymentApplication.Outputs.RefundApiUrl}
Outputs:
  CollectPaymentFunction:
    Value:
      Fn::Sub: ${CollectPayment.Arn}
    Description: Collect Payment Lambda Function
  RefundPaymentFunction:
    Value:
      Fn::Sub: ${RefundPayment.Arn}
    Description: Refund Payment Lambda Function
  PaymentCaptureUrl:
    Value:
      Fn::Sub: ${StripePaymentApplication.Outputs.CaptureApiUrl}
    Description: Payment Endpoint for capturing payments
  PaymentChargeUrl:
    Value:
      Fn::Sub: ${StripePaymentApplication.Outputs.ChargeApiUrl}
    Description: Payment Endpoint for collecting payments
  RefundApiUrl:
    Value:
      Fn::Sub: ${StripePaymentApplication.Outputs.RefundApiUrl}
    Description: Payment Endpoint for refunding payments
